version: "3.0"
services:
  google-sheets:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "google-sheets"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      PROJECT_ID": "your-google-cloud-project-name"
      PRIVATE_KEY_ID: "private-key-id-from-json-file"
      PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nsdbahfjkyvagnsdjfnaknfhi3n12312f\n-----END PRIVATE KEY-----\n"
      CLIENT_EMAIL: "your-google-cloud-client-email"
      CLIENT_ID: "client-id-from-json-file"
      SPREADSHEET_TITLE: "mySpreadsheet"
      WORKSHEET_TITLE: "Sheet1"
      COLUMN_HEADERS: False
    ports:
      - 80:80
